services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      TZ: ${TZ:-UTC}
      PORT: ${PORT:-3000}
      HOST: ${HOST:-0.0.0.0}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      APP_KEY: ${APP_KEY:-28376iufbiwcgu8wbb}
      DEBUG: ${DEBUG:-false}
      DB_HOST: ${DB_HOST:-postgres-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      DB_NAME: ${DB_NAME:-dev}
      JWT_SECRET: ${JWT_SECRET:-3476vcyhxskcbgrvh}
      SESSION_DRIVER: ${SESSION_DRIVER:-cookie}
      DRIVE_DISK: ${DRIVE_DISK:-fs} # fs #s3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-xxxxxxxxxx}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-xxxxxxxxxx}
      AWS_REGION: ${AWS_REGION:-xxxxxxxxxx}
      S3_BUCKET: ${S3_BUCKET:-xxxxxxxxxx}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    depends_on:
      - postgres-db
    networks:
      - backend

  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${postgres}
    volumes:
      - postgres-database-16:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - backend

volumes:
  postgres-database-16:

networks:
  backend:
    driver: bridge
