services:
  server:
    build:
      context: .
    environment:
      - NODE_ENV=production
      - TZ=UTC
      - PORT=3000
      - HOST=localhost
      - LOG_LEVEL=info
      - APP_KEY=DEsoriyyHSO9a_SlA37U0ZZ0BWJIlvfciugduig
      - DEBUG=false
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=dev
      - JWT_SECRET=weirgf3w45vtgwsdfq3bhbggfurtieytgv
      - SESSION_DRIVER=cookie
      - DRIVE_DISK=fs #s3  #fs
      - AWS_ACCESS_KEY_ID=XXXXXXXXXX
      - AWS_SECRET_ACCESS_KEY=XXXXXXXXXX
      - AWS_REGION=XXXXXXXXXX
      - S3_BUCKET=XXXXXXXXXX
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - '5432'
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
    driver: bridge
