apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-bucket
  labels:
    app: s3-bucket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-bucket
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: s3-bucket
    spec:
      containers:
        - name: s3-bucket
          image: docker.cluster.absol.in/s3-bucket:v2
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgresql-0.postgresql-service.postgresql.svc.cluster.local
          envFrom:
            - secretRef:
                name: s3-bucket-secrets
      imagePullSecrets:
        - name: registry-secret
