apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - secrets.yaml
  - Ingress.yaml
  - registry-secrets.yaml

commonLabels:
  app: api

replicas:
  - name: api
    count: 1

images:
  - name: docker.cluster.absol.in/api
    newTag: v1
